name: neuerspuki
favicon: null
layout_spectrum: 0.85309
typography_spectrum: 0.7114695
title: Sebastian Katzer
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011334'
    - '#eaebd9'
    - '#6c6877'
    - '#de6641'
    - '#a52440'
  brandStrength: 0.0625
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
