title: Sebastian Katzer
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  lightness: 0.125
  brandStrength: 0.1684588
  brandColors:
    - '#011334'
    - '#eaebd9'
    - '#6c6877'
    - '#de6641'
    - '#a52440'
  rhythmicContrast: 0.6075269
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: neuerspuki
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.7114695
layout_spectrum: 1
