title: Sebastian Katzer
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  lightness: 0.8512545
  brandStrength: 0.4713262
  brandColors:
    - '#011334'
    - '#eaebd9'
    - '#6c6877'
    - '#de6641'
    - '#a52440'
  rhythmicContrast: 0.5716846
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: neuerspuki
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3172043
layout_spectrum: 0.2849462
