name: neuerspuki
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74265
title: Sebastian Katzer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011334'
    - '#eaebd9'
    - '#6c6877'
    - '#de6641'
    - '#a52440'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
