name: neuerspuki
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3606695947237313
title: Neuer Spuki
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011334'
    - '#eaebd9'
    - '#6c6877'
    - '#de6641'
    - '#a52440'
  brandStrength: 0.3125
  lightness: 0.36155772604979575
  saturation: 0.625
  rhythmicContrast: 0.2808877530042082
purpose: []
